[package]
name = "day17"
version = "0.1.0"
authors = ["Adrian Chitescu <achitescu@bitdefender.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
int_computer= { path= "../int_computer" }
itertools="0.8.2"
